spring.application.name=groupware

server.port=8080

# MariaDB 데이터소스 설정
spring.datasource.url=jdbc:mariadb://100.53.233.206:3306/groupware?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
# spring.datasource.url=jdbc:mariadb://mariadb-server:3306/imageboard?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.username=human
spring.datasource.password=human
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

spring.mvc.hiddenmethod.filter.enabled=true